# Generated by Django 4.2.15 on 2024-09-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_remove_profile_skills_profile_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="job_role_1",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="job_role_2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="job_role_3",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
