# Generated by Django 4.2.15 on 2024-09-12 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_profile_job_role_1_profile_job_role_2_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="contact_details",
            new_name="phone",
        ),
    ]
