# Generated by Django 4.2.15 on 2024-09-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_rename_contact_details_profile_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workexperience",
            name="end_date",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="start_date",
            field=models.CharField(max_length=7),
        ),
    ]
