# Generated by Django 4.2.15 on 2024-09-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_alter_workexperience_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certification",
            name="date_obtained",
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name="education",
            name="end_date",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="start_date",
            field=models.CharField(max_length=7),
        ),
    ]
